# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC101' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RAC101
  pod 'ReactiveObjC', '~> 3.1.1'

  target 'RAC101Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC101UITests' do
    # Pods for testing
  end

end
