# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RXSwift103_CollectionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RXSwift103_CollectionDemo
  pod 'RxSwift', '~> 6.1.0'
  pod 'RxCocoa', '~> 6.1.0'
  pod 'RxDataSources', '~> 5.0.0'

  target 'RXSwift103_CollectionDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RXSwift103_CollectionDemoUITests' do
    # Pods for testing
  end

end
