# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '01_MGJRouterDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 01_MGJRouterDemo  
  pod 'MGJRouter', '~> 0.10.0'


  target '01_MGJRouterDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '01_MGJRouterDemoUITests' do
    # Pods for testing
  end

end
