# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC102_RxSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RAC102_RxSwiftDemo
  pod 'RxSwift', '~> 6.1.0'
  pod 'RxCocoa', '~> 6.1.0'

  target 'RAC102_RxSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC102_RxSwiftDemoUITests' do
    # Pods for testing
  end

end
