# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '002_GCDAsyncSocket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 002_GCDAsyncSocket
  pod 'CocoaAsyncSocket', '~> 7.6.5'

  target '002_GCDAsyncSocketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '002_GCDAsyncSocketUITests' do
    # Pods for testing
  end

end
