# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '001_OCMock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 001_OCMock

  target '001_OCMockTests' do
    inherit! :search_paths
    pod 'OCMock', '~> 3.8.1'
    # Pods for testing
  end

  target '001_OCMockUITests' do
    # Pods for testing
  end

end
