# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '025_GPUImageDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 025_GPUImageDemo
  pod 'GPUImage', '~> 0.1.7'

  target '025_GPUImageDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '025_GPUImageDemoUITests' do
    # Pods for testing
  end

end
