# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '13_UserResponsibility' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 13_UserResponsibility
  pod 'RegExCategories', '~> 1.0'

  target '13_UserResponsibilityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '13_UserResponsibilityUITests' do
    # Pods for testing
  end

end
