# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '03_QQDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 03_QQDemo
  pod 'YYKit',           '~> 1.0.9'
  pod 'CocoaLumberjack', '~> 3.6.2'
  pod 'DYFactoryKit',    '~> 0.1.2'

end
