# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo01_RxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for Demo01_RxSwift
  pod 'RxSwift', '~> 5.0.0'
  pod 'RxCocoa', '~> 5.0.0'

end
