# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC102_AFN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RAC102_AFN
  pod 'ReactiveObjC', '~> 3.1.1'
  pod 'AFNetworking', '~> 4.0.1'

  target 'RAC102_AFNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC102_AFNUITests' do
    # Pods for testing
  end

end
