# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '01_PraiseAnimation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 01_PraiseAnimation
  pod 'YYKit',           '~> 1.0.9'
  pod 'CocoaLumberjack', '~> 3.6.2'
  pod 'DYFactoryKit',    '~> 0.1.2'

  target '01_PraiseAnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '01_PraiseAnimationUITests' do
    # Pods for testing
  end

end
